### PR TITLE
New four-note midfield auto

### PR DESCRIPTION
**Pull request by ishaan-sen**

### CODE REVIEW

**Comment by Omnikar** [comment]
Has the blue side been updated with the changes from yesterday yet?

**Comment by ishaan-sen** [comment]
> Has the blue side been updated with the changes from yesterday yet?

no

**Comment by Omnikar** [comment]
Noted.

**Comment by ishaan-sen** [comment]
Done

**Comment by ishaan-sen** [comment]
cant review my own pr, so i had to merge directly

**Pull request merged**
